### ISSUE TITLE
Возможность sql иньекций в запросах

### ISSUE THREAD

**Issue by Zagrebelin** [Kingistel/Galvarda-public#1]
f'Select ... Where id={str(id)}' неплохо ломается, если передать 1 or true в параметрах.

**Comment by Kingistel** [comment]
Просьба написать рабочую инъекцию, для сайта выделяется пользователь который может только в SELECT.

**Comment by Zagrebelin** [comment]
что-то типа `lib/book/1%20or%20true;`
в сочетании с `cursor.fetchall()`  и декартовым произведением 4 таблиц даст чрезмеруню нагрузку по памяти и cpu и на базу данных, и на приложение, что в свобю очередь может дасть отказ в обслуживании при первом же запросе.

**Comment by Kingistel** [comment]
> что-то типа `lib/book/1%20or%20true;` в сочетании с `cursor.fetchall()` и декартовым произведением 4 таблиц даст чрезмеруню нагрузку по памяти и cpu и на базу данных, и на приложение, что в свобю очередь может дасть отказ в обслуживании при первом же запросе.

Ни сервер базы данных(orange pi zero 3), ни сервер сайта(мой пк) не упали. Я достаточно плохо пишу код что бы он просто вернул 404 через пару секунд. В прочем нагрузки тоже не было, надо дальше смотреть. Я не буду экранировать входные пока не будет первого успешного случая.
